version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Pre-Build
      - echo ${ENVIRONMENT}
      - node --version
      - npm --version
      - npm install
      - npm run predeploy:${ENVIRONMENT}
  build:
    commands:
      - echo Building
      - npm run deploy:${ENVIRONMENT}
  post_build:
    finally:
      - echo Build Completed
