AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  HostedZone:
    AllowedValues:
      - gracemedicalvillagedev.com
      - gracemedicalvillage.com
    Type: String

Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Aliases:
          - !Join [
              '',
              [
                !Ref 'AWS::StackName',
                !Ref 'AWS::AccountId',
                .,
                !Ref 'AWS::Region',
                .,
                !Ref 'HostedZone',
              ],
            ]
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Origins:
          - CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
            DomainName: !Join [
                '',
                [
                  !Ref 'S3BucketForWebsiteContent',
                  !FindInMap [
                    Region2S3WebsiteSuffix, # .s3-website-us-east-1.amazonaws.com
                    !Ref 'AWS::Region',
                    Suffix,
                  ],
                ],
              ]
            Id: only-origin
  WebsiteDNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      Comment: CNAME redirect custom name to CloudFront distribution
      Name:
        !Join [
          '',
          [
            !Ref 'AWS::StackName',
            !Ref 'AWS::AccountId',
            .,
            !Ref 'AWS::Region',
            .,
            !Ref 'HostedZone',
          ],
        ]
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt [WebsiteCDN, DomainName]
Outputs:
  WebsiteURL:
    Value: !Join ['', ['http://', !Ref 'WebsiteDNSName']]
    Description: The URL of the newly created website
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content
