AWSTemplateFormatVersion: 2010-09-09
Description: >
  Builds the S3 Bucket for the webapp; Optionally builds the CloudFront Distribution for production

Parameters:
  distributionId:
    AllowedValues:
      - TODO
      - TODO2
    Description: CloudFront distribution ID
    Type: String

  environment:
    AllowedValues:
      - development
      - production
    Description: Can be used to alter resources depending on environment
    Type: String

  resourcePrefix:
    AllowedValues:
      - gmv-client-dev
      - gmv-client-prod
    Type: String

  rootDomainName:
    AllowedValues:
      - gracemedicalvillagedev.com
      - gracemedicalvillage.com
    Type: String

  s3HostedZoneId:
    Default: Z3AQBSTGFYJSTF
    Type: String

  websiteEndpoint:
    Default: s3-website-us-east-1.amazonaws.com
    Type: String

Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref rootDomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub www.${rootDomainName}
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref rootDomainName
  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref rootDomainName
      Comment: Zone apex alias.
      RecordSets:
        - Name: !Ref rootDomainName
          Type: A
          AliasTarget:
            HostedZoneId: !Ref s3HostedZoneId
            DNSName: !Ref websiteEndpoint
        - Name: !Ref rootDomainName
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !GetAtt WWWBucket.DomainName

  # myDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName: mybucket.s3.amazonaws.com
  #           Id: myS3Origin
  #           S3OriginConfig:
  #             OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
  #       Enabled: "true"
  #       Comment: Some comment
  #       DefaultRootObject: index.html
  #       Logging:
  #         IncludeCookies: "false"
  #         Bucket: mylogs.s3.amazonaws.com
  #         Prefix: myprefix
  #       Aliases:
  #         - mysite.example.com
  #         - yoursite.example.com
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #           - DELETE
  #           - GET
  #           - HEAD
  #           - OPTIONS
  #           - PATCH
  #           - POST
  #           - PUT
  #         TargetOriginId: myS3Origin
  #         ForwardedValues:
  #           QueryString: "false"
  #           Cookies:
  #             Forward: none
  #         TrustedSigners:
  #           - 1234567890EX
  #           - 1234567891EX
  #         ViewerProtocolPolicy: allow-all
  #       PriceClass: PriceClass_200
  #       Restrictions:
  #         GeoRestriction:
  #           RestrictionType: whitelist
  #           Locations:
  #             - AQ
  #             - CV
  #       ViewerCertificate:
  #         CloudFrontDefaultCertificate: "true"

Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
